on:
  push:
    branches:
    - main
    
jobs:
  sync:
    runs-on: ubuntu-18.04
    steps:
    - name: sync to coding
      run: |
        git fetch https://${{ secrets.CODING_KEY }}:${{ secrets.CODING_TOKEN }}@e.coding.net/vilex/vilex/vilex.git
        git push -f https://${{ secrets.CODING_KEY }}:${{ secrets.CODING_TOKEN }}@e.coding.net/vilex/vilex/vilex.git HEAD:github/main
